#PBS -N colltest
#PBS -l nodes=4:ppn=8
#PBS -j oe

cd $PBS_O_WORKDIR
log_folder=~/logs_4_8
src_folder=~/course

rm -rf $log_folder
mkdir $log_folder
cd $src_folder
for size in 8 16 32 64 128 256 512 ; do
    make clean
    make nbyte=$size > /dev/null
    mpiexec ./test > ${log_folder}/vdg_bc_${size}.log 2>&1
    make clean
    make nbyte=$size mpi_bc=1 > /dev/null
    mpiexec ./test > ${log_folder}/mpi_bc_${size}.log 2>&1
done


